### PR TITLE
Fixing variable naming mismatch

### PR DESCRIPTION
**Pull request by pedroserano**
Fixes the undefined call problem when calling for isOccupied for both js scripts and the homebridge plugin - the variable works when the name 'sensor' matches 'sensor' - like the other functions of the fan (light, fan, etc all match their variables).

### CODE REVIEW

**Comment by sean9keenan** [comment]
Ahhh, awesome! Thanks for catching this, I see you also have a PR in the corresponding Homebridge API! As soon as this gets merged in I'll promote it on NPM and then merge in the Homebridge one.

Two quick things:

- Did you test the `smartmodeactual` or `smartmodestate` functions? It's possible that those are supposed to be their own `smartmode` property (and I just _completely_ messed up that section of the code) - but I forget what the dump from wireshark looks like, so it's possible that they are under the `sensor`.
- It's not a huge deal - but I figure I'd mention it because some people really care: It's good practice to squash your commits just to make the commit history cleaner.

In case you haven't done this before: The way I normally do this is by running `git rebase --interactive` (Passing in the commit you want to go back to), eg in this case you can do `git rebase --interactive 	c49882c` and then either squash your commits or just pick the last one. And then pushing the branch again - but this time since you've changed the history you'll have to push with `--force`. If you do this it will automatically update the history on this PR, even though you've changed the history.

**Comment by sean9keenan** [comment]
What I meant by the `smartmode` comment was that this section of the code might actually have to be:

```
    this.smartmode = new BigAssProperty('smartmode', this);
    this.smartmode.createGetField('smartmodeactual', ['SMARTMODE', 'ACTUAL'], true, undefined, 'OFF', 'COOLING', 'HEATING'); // Heating smartmode invokes LEARN;STATE;OFF and FAN;PWR;ON and FAN;SPD;ACTUAL;1 and WINTERMODE;STATE;ON and SMARTMODE;STATE;HEATING and SMARTMODE;ACTUAL;HEATING
    this.smartmode.createGetField('smartmodestate', ['SMARTMODE', 'STATE'], true, undefined, 'LEARN', 'COOLING', 'HEATING', 'FOLLOWSTAT'); // FOLLOWSTAT is the works with nest option, it is followed by SMARTMODE;ACTUAL;OFF command
```

**Comment by pedroserano** [comment]
I gotcha. As far as I can tell as long as this."variable" matches the new BigAssProperty('"variable"'... the api works. I think you're right though, it makes more sense to keep the smartmode as smartmode because that's how the fan reports it when you request a full update. I will try to revert those changes.

**Comment by sean9keenan** [comment]
Pulled in #9 instead, thanks again!

**Pull request closed without merging**
